{% set name = "mapd-core-cpu" %}
{% set version = "4.0.1" %}
{% set sha256 = "4e49bf3a9453188b4aec4f8f1318f1ffb381412cf6e85488b07bdaab6808cc1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mapd/mapd-core/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
    - clangdev 4.0.0
    - llvmdev 4.0.0
    - git
  host:
    - arrow-cpp 0.7.1
    - bisonpp
    - boost-cpp 1.65.0
    - double-conversion
    - flex
    - folly
    - go
    - gperftools
    - gdal
    - glog
    - gflags
    - openjdk 8
    - openssl
    - maven
    - libarchive  # [osx]
    - libpng
    - llvmdev
    - libkml
    - thrift-cpp 0.11.0
    - thrift 0.11.0
  run:
    - arrow-cpp 0.7.1
    - bisonpp
    - boost-cpp
    - double-conversion
    - flex
    - folly
    - go
    - gperftools
    - gdal
    - glog
    - gflags
    - openjdk 8
    - openssl
    - maven
    - libarchive  # [osx]
    - libpng
    - llvmdev
    - libkml
    - thrift-cpp 0.11.0

about:
  home: https://www.mapd.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'The MapD Core database'

  description: |
    MapD Core is an in-memory, column store, SQL relational database 
    that was designed from the ground up to run on GPUs.
  doc_url: https://www.mapd.com/docs/
  dev_url: https://github.com/mapd/mapd-core

extra:
  recipe-maintainers:
    - xmnlab
    - pearu
