{% set name = "mapd-core-cpu" %}
{% set version = "4.0.1" %}
{% set sha256 = "4e49bf3a9453188b4aec4f8f1318f1ffb381412cf6e85488b07bdaab6808cc1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mapd/mapd-core/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
  run:
    - llvmdev  # [osx]
    - go  # [osx]
    - boost  # [osx]
    - openjdk  # [osx]
    - gperftools  # [osx]
    - gdal  # [osx]
    - arrow-cpp 0.7.1  # [osx]

about:
  home: https://www.mapd.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'The MapD Core database'

  description: |
    MapD Core is an in-memory, column store, SQL relational database 
    that was designed from the ground up to run on GPUs.
  doc_url: https://www.mapd.com/docs/
  dev_url: https://github.com/mapd/mapd-core

extra:
  recipe-maintainers:
    - xmnlab
    - pearu
